### ISSUE TITLE
dependencies compatibility

### ISSUE THREAD

**Issue by Denys88** [hyintell/COOM#1]
Hi!
I've got an issue with dependency versions.
First of all I think TF 2.5 should be totally optional. I am using pytorch and don't want to install TF.
Second one:
Your library requires  "numpy==1.19.5".
But gymnasium 0.28.0 depends on numpy>=1.21.0 and tensorflow 2.5.0 depends on numpy~=1.19.2.
As result I have no chance of installing your env.

**Comment by TTomilin** [comment]
Hi!
Thank you very much for pointing this out!
Indeed, there were cross-dependencies between the environments and training sections, even dependency version conflicts as you correctly pointed out.
The project has now been split up into separate modules, such that the default install will now only regard the environments and not the training code.
Please let us know if there are any further issues!
